server:
  port: 8888

spring:
  application:
    name: project

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring
    username: spring
    password: spring
  
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security: 
  jwt: 
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000

logging: 
  level:
    org:
      springframework:
        security: DEBUG